# a large docker image with python3.11, nodejs, and git

FROM mcr.microsoft.com/devcontainers/base:ubuntu

ENV NODE_MAJOR=20
ENV DEBIAN_FRONTEND="noninteractive"

RUN apt update && \
    apt install -y \
    software-properties-common \
    curl \
    ca-certificates \
    gnupg

RUN add-apt-repository ppa:deadsnakes/ppa

RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt update && \
    apt install -y \
    build-essential \
    git \
    python3.11 \
    python3.11-dev \
    python3.11-venv \
    python3.11-distutils \
    wget \
    nodejs

RUN python3.11 -m ensurepip
